### ISSUE TITLE
[FEATURE] Installation script

### ISSUE THREAD

**Issue by randomtwdude** [dmyTRUEk/gensoquote#1]
I wrote a simple bash script to install gensoquote. (part of the fumosay-gensoquote wrapper script)
[gensoquote_install.txt](https://github.com/dmyTRUEk/gensoquote/files/14585441/gensoquote_install.txt)

- It reminds you to install the dependencies (`curl` and `git`)
- It handles installing `cargo` automatically, if needed
- Installs to `/usr/local/bin`
- Tested on Debian WSL2

**Comment by dmyTRUEk** [comment]
I honestly don't think creating single "general" install script is good practice. There are a lot of problems with it and almost infinite amount of possibilities that you would need to cover.

For example your `gensoquote_install.txt` (and probably any other humanly written install script would) have at least this problems:
1. Even `/bin/bash` itself may not exist or be at another location, for example like in nixos, it's located at `/nix/store/mb82447z77gwh2vfsmvj03qq141c6rph-system-path/bin/bash`, or any other os that doesn't use [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard).
2. Person installing program may \<not \<want / \<be able\>\> / \<prefer other implementations\>\> to use any of commands that script uses, such as `curl` (maybe they prefer `wget` or any other), `git` (maybe they like [gix](https://github.com/Byron/gitoxide)) and so on.
3. On most linux distros prefered way of installing anything (rust/cargo including) is through package manager instead of script from the internet.
4. Installing program to `/usr/local/bin` (even in case of FHS) means that firstly you need root access and secondly it is will be available to all users of pc
5. It only works on Debian and Ubuntu (and all their derivatives) which are only about third of all linux user. But what about two thirds of other? Like Fedora and all it's derivatives, Arch and all it's derivatives, not to mention all other distros that are "different" like NixOS, Gentoo, Linux From Scratch and so on? Supporting them all (or even three main: Debian, Fedora, Arch) seems extremely hard task for me and i honestly don't want to be cause of someone's problems, like on Pop_OS! when you installed Steam you could break your entire desktop.

And that's not even considering it from the security and bugs point.

**Comment by randomtwdude** [comment]
Those are some good points!
